language: php

notifications:
  email:
    recipients:
      - luciano.bargmann@gmail.com
    on_success: never
    on_failure: always

# Handle git submodules yourself
git:
    submodules: false


php:
  - 5.5.9

before_install:
  - php composer.phar self-update
# Use sed to replace the SSH URL with the public URL, then initialize submodules
#  - sed -i 's/git@github.com:/https:\/\/tudommn:tudommn2014@github.com\//' .gitmodules
#  - git submodule update --init --recursive

before_script:
#  - export USE_ZEND_ALLOC=0
  - composer install -n
  - phpenv config-add travis.php.ini
  - php -i

#install:
#  - php -S 127.0.0.1:8000 payum/web/index.php
    
script:
 - rm app/cache/** -R -f
 - mkdir -p build/logs
 - phpunit -d memory_limit=-1 -d zend.enable_gc=0 -c app
# - phpunit -d memory_limit=-1 -d zend.enable_gc=0 -c app --coverage-clover build/logs/clover.xml
# - php build/coverage-checker.php build/logs/clover.xml 50

branches:
  only:
    - master
    - development
