language: php
sudo: false

notifications:
  email:
    recipients:
      - luciano.bargmann@gmail.com
    on_success: never
    on_failure: always

# Handle git submodules yourself
git:
    submodules: false


php:
  - 5.5.9

env:
  - SYMFONY_VERSION=2.3.*

before_script:
  - composer install -n
  - vendor/symfony-cmf/testing/bin/travis/phpcr_odm_doctrine_dbal.sh
  - php -i

script:
 - rm app/cache/** -R -f
 - mkdir -p build/logs
 - phpunit -d memory_limit=-1 -d zend.enable_gc=0 -c app
# - phpunit -d memory_limit=-1 -d zend.enable_gc=0 -c app --coverage-clover build/logs/clover.xml
# - php build/coverage-checker.php build/logs/clover.xml 50

branches:
  only:
    - master
    - development
