language: php
sudo: false

notifications:
  email:
    recipients:
      - luciano.bargmann@gmail.com
    on_success: never
    on_failure: always

# Handle git submodules yourself
git:
    submodules: false


php:
  - 5.5.9

before_script:
  - composer install -n
  - php -i
  - mysql -e 'create database symfony;'
  - php app/console doctrine:schema:create --force


script:
 - rm app/cache/** -R -f
 - mkdir -p build/logs
 - phpunit -d memory_limit=-1 -d zend.enable_gc=0 -c app
# - phpunit -d memory_limit=-1 -d zend.enable_gc=0 -c app --coverage-clover build/logs/clover.xml
# - php build/coverage-checker.php build/logs/clover.xml 50

branches:
  only:
    - master
    - development
