parameters:
#    hckt_planet_foundation.example.class: HcktPlanet\FoundationBundle\Example

services:
    hckt_planet_foundation.user_manager:
      class: HcktPlanet\FoundationBundle\Entity\UserManager
      arguments: [@security.encoder_factory,@fos_user.util.username_canonicalizer,@fos_user.util.email_canonicalizer,@fos_user.entity_manager,%fos_user.model.user.class%]

#    hckt_planet_foundation.example:
#        class: %hckt_planet_foundation.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
