parameters:
#    hckt_planet_foundation.example.class: HcktPlanet\FoundationBundle\Example

services:
#    hckt_planet_foundation.example:
#        class: %hckt_planet_foundation.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
